\chapter{Opérations sur les tables de données}

\section{Travail sur les lignes et colonnes}

Dans une grande variété de situations, il peut être avantageux de répéter une opération sur toutes les lignes, ou toutes les colonnes.
R propose une fonction pour automatiser ce traitement, \emph{via} la fonction \texttt{apply}. 

<<>>=
dat = matrix(rnorm(100),nrow=10)
apply(dat,1,mean)
apply(dat,2,var)
@ 

\section{Traitement des données}

\section{Division et traitement par niveau}